ta: update health checks and CI

diff --git a/.github/workflows/CICD.yaml b/.github/workflows/CICD.yaml
--- a/.github/workflows/CICD.yaml
+++ b/.github/workflows/CICD.yaml
@@ -501,40 +501,32 @@ jobs:
           token: ${{ secrets.ICE_CI_CD_BOT_GH_PAT }}
           path: secret-infrastructure
           fetch-depth: 0
-      - name: Update [staging] application tag version in helm/heimdall-identity-io/staging/common-values.yaml
+      - name: Update application tag versions
         uses: mikefarah/yq@master
         with:
           cmd: |
+            SERVICES="heimdall-identity-io heimdall-asset-data-syncer heimdall-token-analytics"
+            ENVIRONMENTS="staging testnet"
+            set -xe
             cd secret-infrastructure
-            yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' helm/heimdall-identity-io/staging/common-values.yaml
-      - name: Update [staging] application tag version in helm/heimdall-asset-data-syncer/staging/common-values.yaml
-        uses: mikefarah/yq@master
-        with:
-          cmd: |
-            cd secret-infrastructure
-            yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' helm/heimdall-asset-data-syncer/staging/common-values.yaml
-      - name: Update [testnet] application tag version in helm/heimdall-identity-io/testnet/common-values.yaml
-        uses: mikefarah/yq@master
-        with:
-          cmd: |
-            cd secret-infrastructure
-            yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' helm/heimdall-identity-io/testnet/common-values.yaml
-      - name: Update [testnet] application tag version in helm/heimdall-asset-data-syncer/testnet/common-values.yaml
-        uses: mikefarah/yq@master
-        with:
-          cmd: |
-            cd secret-infrastructure
-            yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' helm/heimdall-asset-data-syncer/testnet/common-values.yaml
+            for SERVICE in ${SERVICES}; do
+              for ENV in ${ENVIRONMENTS}; do
+                FILE_PATH="helm/${SERVICE}/${ENV}/common-values.yaml"
+                echo "Updating ${FILE_PATH}..."
+                if [ -f "$FILE_PATH" ]; then
+                  yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' "${FILE_PATH}"
+                  git add "${FILE_PATH}"
+                else
+                  echo "Warning: ${FILE_PATH} not found, skipping"
+                fi
+              done
+            done
       - name: Commit and Push Changes to Application Tag Version
         run: |
           cd secret-infrastructure
           git config user.name "ice CI/CD Bot"
           git config user.email ice-cicd-bot@ice.vip
-          git add helm/heimdall-identity-io/staging/common-values.yaml
-          git add helm/heimdall-asset-data-syncer/staging/common-values.yaml
-          git add helm/heimdall-identity-io/testnet/common-values.yaml
-          git add helm/heimdall-asset-data-syncer/testnet/common-values.yaml
-          git commit -m "Updated 'heimdall-identity-io' && 'heimdall-asset-data-syncer' tag version (${{env.APP_TAG}}) in application helm chart deployment manifests"
+          git commit -m "Updated 'heimdall' tag version (${{env.APP_TAG}}) in application helm chart deployment manifests"
           git push --set-upstream origin master
       - name: Slack Notification For Success
         if: ${{ success() }}
